### ISSUE TITLE
Add answers to existing questions

### ISSUE THREAD

**Issue by hjaintech** [hjaintech/interview-prep#2]
Add answers to existing questions

**Comment by harlyon** [comment]
I had a permission denied when pushing to the branch I created...
can you advise on this

**Comment by hjaintech** [comment]
@harlyon Please check out the steps to raise the PR (refer [here](https://github.com/PointCloudLibrary/pcl/wiki/A-step-by-step-guide-on-preparing-and-submitting-a-pull-request)). Ideally you would have to fork this repo, make changes in your forked repo and then raise a PR.
