### ISSUE TITLE
Embed videos in markdown

### ISSUE THREAD

**Issue by hjaintech** [hjaintech/interview-prep#4]
For the solution of question 9, instead of having just links to youtube videos, those videos should be embedded in the readme itself so that user doesn't have to navigate to youtube to watch them. Also it would help to give them a preview of videos on this page itself.

**Comment by wale-bant** [comment]
Hi, I'll love to ok implement this feature. Should I get started?

**Comment by hjaintech** [comment]
@wale-bant Sure. Go ahead. I believe there should be an existing way to do this.

**Comment by wale-bant** [comment]
Great. I'm on it.

**Comment by wale-bant** [comment]
Done. Please review my PR #10 and merged.
