### ISSUE TITLE
Anchors in readme.md not working where there are question marks.

### ISSUE THREAD

**Issue by hjaintech** [hjaintech/interview-prep#6]
Anchors in readme.md not working where there are question marks.

**Comment by BosEriko** [comment]
Can I take this one?

**Comment by hjaintech** [comment]
sure @BosEriko .

**Comment by BosEriko** [comment]
@hjaintech hello. I made a PR. :)

**Comment by hjaintech** [comment]
Thanks @BosEriko . PR #9 fixed this issue. Thus closing it.
